from app.db.enums import UserRole


CREATE_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.JUNIOR_ADMIN}
CANCEL_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN, UserRole.ADMIN}
USER_ADMIN_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN}
MASTER_ROLES = {UserRole.MASTER, UserRole.JUNIOR_MASTER, UserRole.SUPER_ADMIN, UserRole.SYS_ADMIN}
TRANSFER_CONFIRM_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN}
