from app.db.enums import UserRole


CREATE_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.JUNIOR_ADMIN}
CANCEL_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN, UserRole.ADMIN}
USER_ADMIN_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN}
MASTER_ROLES = {UserRole.MASTER, UserRole.SUPER_ADMIN, UserRole.SYS_ADMIN}
TRANSFER_CONFIRM_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN}
JUNIOR_LINK_ADMIN_ROLES = {UserRole.ADMIN, UserRole.SUPER_ADMIN, UserRole.SYS_ADMIN}
FINANCE_SUMMARY_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN}
FINANCE_EXPORT_ROLES = {UserRole.SYS_ADMIN, UserRole.SUPER_ADMIN}
MANUAL_TX_ROLES = {UserRole.ADMIN, UserRole.SUPER_ADMIN, UserRole.SYS_ADMIN}
